name: agro_rover_app
description: Smart Agricultural Rover - Farmer Dashboard App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  cupertino_icons: ^1.0.6

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3

  wifi_iot: ^0.3.19
  connectivity_plus: ^6.0.5
  flutter_mjpeg: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#16A34A"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
